/**
 * List of countries with their ISO 3166-1 alpha-2 codes
 * Used for country selection and flag display
 */
export interface Country {
  code: string;  // ISO 3166-1 alpha-2 code (lowercase for react-circle-flags)
  name: string;
  ioc: string;  // IOC 3-letter code (for sports context)
}

export const COUNTRIES: Country[] = [
  { code: 'af', ioc: 'AFG', name: 'Afghanistan'},
  { code: 'al', ioc: 'ALB', name: 'Albania'},
  { code: 'dz', ioc: 'ALG', name: 'Algeria'},
  { code: 'ad', ioc: 'AND', name: 'Andorra'},
  { code: 'ao', ioc: 'ANG', name: 'Angola'},
  { code: 'ar', ioc: 'ARG', name: 'Argentina'},
  { code: 'am', ioc: 'ARM', name: 'Armenia'},
  { code: 'au', ioc: 'AUS', name: 'Australia'},
  { code: 'at', ioc: 'AUT', name: 'Austria'},
  { code: 'az', ioc: 'AZE', name: 'Azerbaijan'},
  { code: 'bs', ioc: 'BAH', name: 'Bahamas'},
  { code: 'bh', ioc: 'BRN', name: 'Bahrain'},
  { code: 'bd', ioc: 'BAN', name: 'Bangladesh'},
  { code: 'bb', ioc: 'BAR', name: 'Barbados'},
  { code: 'by', ioc: 'BLR', name: 'Belarus'},
  { code: 'be', ioc: 'BEL', name: 'Belgium'},
  { code: 'bz', ioc: 'BIZ', name: 'Belize'},
  { code: 'bj', ioc: 'BEN', name: 'Benin'},
  { code: 'bt', ioc: 'BHU', name: 'Bhutan'},
  { code: 'bo', ioc: 'BOL', name: 'Bolivia'},
  { code: 'ba', ioc: 'BIH', name: 'Bosnia and Herzegovina'},
  { code: 'bw', ioc: 'BOT', name: 'Botswana'},
  { code: 'br', ioc: 'BRA', name: 'Brazil'},
  { code: 'bn', ioc: 'BRU', name: 'Brunei'},
  { code: 'bg', ioc: 'BUL', name: 'Bulgaria'},
  { code: 'bf', ioc: 'BUR', name: 'Burkina Faso'},
  { code: 'bi', ioc: 'BDI', name: 'Burundi'},
  { code: 'cv', ioc: 'CPV', name: 'Cabo Verde'},
  { code: 'kh', ioc: 'CAM', name: 'Cambodia'},
  { code: 'cm', ioc: 'CMR', name: 'Cameroon'},
  { code: 'ca', ioc: 'CAN', name: 'Canada'},
  { code: 'cf', ioc: 'CAF', name: 'Central African Republic'},
  { code: 'td', ioc: 'CHA', name: 'Chad'},
  { code: 'cl', ioc: 'CHI', name: 'Chile'},
  { code: 'cn', ioc: 'CHN', name: 'China'},
  { code: 'co', ioc: 'COL', name: 'Colombia'},
  { code: 'km', ioc: 'COM', name: 'Comoros'},
  { code: 'cg', ioc: 'CON', name: 'Congo'},
  { code: 'cr', ioc: 'CRC', name: 'Costa Rica'},
  { code: 'hr', ioc: 'CRO', name: 'Croatia'},
  { code: 'cu', ioc: 'CUB', name: 'Cuba'},
  { code: 'cy', ioc: 'CYP', name: 'Cyprus'},
  { code: 'cz', ioc: 'CZE', name: 'Czech Republic'},
  { code: 'cd', ioc: 'COD', name: 'Democratic Republic of the Congo'},
  { code: 'dk', ioc: 'DEN', name: 'Denmark'},
  { code: 'dj', ioc: 'DJI', name: 'Djibouti'},
  { code: 'dm', ioc: 'DMA', name: 'Dominica'},
  { code: 'do', ioc: 'DOM', name: 'Dominican Republic'},
  { code: 'ec', ioc: 'ECU', name: 'Ecuador'},
  { code: 'eg', ioc: 'EGY', name: 'Egypt'},
  { code: 'sv', ioc: 'ESA', name: 'El Salvador'},
  { code: 'gq', ioc: 'GNQ', name: 'Equatorial Guinea'},
  { code: 'er', ioc: 'ERI', name: 'Eritrea'},
  { code: 'ee', ioc: 'EST', name: 'Estonia'},
  { code: 'sz', ioc: 'SWZ', name: 'Eswatini'},
  { code: 'et', ioc: 'ETH', name: 'Ethiopia'},
  { code: 'fj', ioc: 'FIJ', name: 'Fiji'},
  { code: 'fi', ioc: 'FIN', name: 'Finland'},
  { code: 'fr', ioc: 'FRA', name: 'France'},
  { code: 'ga', ioc: 'GAB', name: 'Gabon'},
  { code: 'gm', ioc: 'GAM', name: 'Gambia'},
  { code: 'ge', ioc: 'GEO', name: 'Georgia'},
  { code: 'de', ioc: 'GER', name: 'Germany'},
  { code: 'gh', ioc: 'GHA', name: 'Ghana'},
  { code: 'gr', ioc: 'GRE', name: 'Greece'},
  { code: 'gd', ioc: 'GRN', name: 'Grenada'},
  { code: 'gt', ioc: 'GUA', name: 'Guatemala'},
  { code: 'gn', ioc: 'GUI', name: 'Guinea'},
  { code: 'gw', ioc: 'GBS', name: 'Guinea-Bissau'},
  { code: 'gy', ioc: 'GUY', name: 'Guyana'},
  { code: 'ht', ioc: 'HAI', name: 'Haiti'},
  { code: 'hn', ioc: 'HON', name: 'Honduras'},
  { code: 'hu', ioc: 'HUN', name: 'Hungary'},
  { code: 'is', ioc: 'ISL', name: 'Iceland'},
  { code: 'in', ioc: 'IND', name: 'India'},
  { code: 'id', ioc: 'INA', name: 'Indonesia'},
  { code: 'ir', ioc: 'IRI', name: 'Iran'},
  { code: 'iq', ioc: 'IRQ', name: 'Iraq'},
  { code: 'ie', ioc: 'IRL', name: 'Ireland'},
  { code: 'il', ioc: 'ISR', name: 'Israel'},
  { code: 'it', ioc: 'ITA', name: 'Italy'},
  { code: 'jm', ioc: 'JAM', name: 'Jamaica'},
  { code: 'jp', ioc: 'JPN', name: 'Japan'},
  { code: 'jo', ioc: 'JOR', name: 'Jordan'},
  { code: 'kz', ioc: 'KAZ', name: 'Kazakhstan'},
  { code: 'ke', ioc: 'KEN', name: 'Kenya'},
  { code: 'ki', ioc: 'KIR', name: 'Kiribati'},
  { code: 'kw', ioc: 'KUW', name: 'Kuwait'},
  { code: 'kg', ioc: 'KGZ', name: 'Kyrgyzstan'},
  { code: 'la', ioc: 'LAO', name: 'Laos'},
  { code: 'lv', ioc: 'LAT', name: 'Latvia'},
  { code: 'lb', ioc: 'LBN', name: 'Lebanon'},
  { code: 'ls', ioc: 'LES', name: 'Lesotho'},
  { code: 'lr', ioc: 'LBR', name: 'Liberia'},
  { code: 'ly', ioc: 'LBA', name: 'Libya'},
  { code: 'li', ioc: 'LIE', name: 'Liechtenstein'},
  { code: 'lt', ioc: 'LTU', name: 'Lithuania'},
  { code: 'lu', ioc: 'LUX', name: 'Luxembourg'},
  { code: 'mg', ioc: 'MAD', name: 'Madagascar'},
  { code: 'mw', ioc: 'MAW', name: 'Malawi'},
  { code: 'my', ioc: 'MAS', name: 'Malaysia'},
  { code: 'mv', ioc: 'MDV', name: 'Maldives'},
  { code: 'ml', ioc: 'MLI', name: 'Mali'},
  { code: 'mt', ioc: 'MLT', name: 'Malta'},
  { code: 'mh', ioc: 'MHL', name: 'Marshall Islands'},
  { code: 'mr', ioc: 'MRT', name: 'Mauritania'},
  { code: 'mu', ioc: 'MUS', name: 'Mauritius'},
  { code: 'mx', ioc: 'MEX', name: 'Mexico'},
  { code: 'fm', ioc: 'FSM', name: 'Micronesia'},
  { code: 'md', ioc: 'MDA', name: 'Moldova'},
  { code: 'mc', ioc: 'MON', name: 'Monaco'},
  { code: 'mn', ioc: 'MGL', name: 'Mongolia'},
  { code: 'me', ioc: 'MNE', name: 'Montenegro'},
  { code: 'ma', ioc: 'MAR', name: 'Morocco'},
  { code: 'mz', ioc: 'MOZ', name: 'Mozambique'},
  { code: 'mm', ioc: 'MYA', name: 'Myanmar'},
  { code: 'na', ioc: 'NAM', name: 'Namibia'},
  { code: 'nr', ioc: 'NRU', name: 'Nauru'},
  { code: 'np', ioc: 'NEP', name: 'Nepal'},
  { code: 'nl', ioc: 'NED', name: 'Netherlands'},
  { code: 'nz', ioc: 'NZL', name: 'New Zealand'},
  { code: 'ni', ioc: 'NIC', name: 'Nicaragua'},
  { code: 'ne', ioc: 'NIG', name: 'Niger'},
  { code: 'ng', ioc: 'NGR', name: 'Nigeria'},
  { code: 'kp', ioc: 'PRK', name: 'North Korea'},
  { code: 'mk', ioc: 'MKD', name: 'North Macedonia'},
  { code: 'no', ioc: 'NOR', name: 'Norway'},
  { code: 'om', ioc: 'OMA', name: 'Oman'},
  { code: 'pk', ioc: 'PAK', name: 'Pakistan'},
  { code: 'pw', ioc: 'PLW', name: 'Palau'},
  { code: 'ps', ioc: 'PLE', name: 'Palestine'},
  { code: 'pa', ioc: 'PAN', name: 'Panama'},
  { code: 'pg', ioc: 'PNG', name: 'Papua New Guinea'},
  { code: 'py', ioc: 'PAR', name: 'Paraguay'},
  { code: 'pe', ioc: 'PER', name: 'Peru'},
  { code: 'ph', ioc: 'PHI', name: 'Philippines'},
  { code: 'pl', ioc: 'POL', name: 'Poland'},
  { code: 'pt', ioc: 'POR', name: 'Portugal'},
  { code: 'qa', ioc: 'QAT', name: 'Qatar'},
  { code: 'ro', ioc: 'ROM', name: 'Romania'},
  { code: 'ru', ioc: 'RUS', name: 'Russia'},
  { code: 'rw', ioc: 'RWA', name: 'Rwanda'},
  { code: 'kn', ioc: 'SKN', name: 'Saint Kitts and Nevis'},
  { code: 'lc', ioc: 'LCA', name: 'Saint Lucia'},
  { code: 'vc', ioc: 'VCT', name: 'Saint Vincent and the Grenadines'},
  { code: 'ws', ioc: 'WSM', name: 'Samoa'},
  { code: 'sm', ioc: 'SMR', name: 'San Marino'},
  { code: 'st', ioc: 'STP', name: 'Sao Tome and Principe'},
  { code: 'sa', ioc: 'KSA', name: 'Saudi Arabia'},
  { code: 'sn', ioc: 'SEN', name: 'Senegal'},
  { code: 'rs', ioc: 'SRB', name: 'Serbia'},
  { code: 'sc', ioc: 'SYC', name: 'Seychelles'},
  { code: 'sl', ioc: 'SLE', name: 'Sierra Leone'},
  { code: 'sg', ioc: 'SIN', name: 'Singapore'},
  { code: 'sk', ioc: 'SVK', name: 'Slovakia'},
  { code: 'si', ioc: 'SLO', name: 'Slovenia'},
  { code: 'sb', ioc: 'SOL', name: 'Solomon Islands'},
  { code: 'so', ioc: 'SOM', name: 'Somalia'},
  { code: 'za', ioc: 'RSA', name: 'South Africa'},
  { code: 'kr', ioc: 'KOR', name: 'South Korea'},
  { code: 'ss', ioc: 'SSD', name: 'South Sudan'},
  { code: 'es', ioc: 'ESP', name: 'Spain'},
  { code: 'lk', ioc: 'SRI', name: 'Sri Lanka'},
  { code: 'sd', ioc: 'SUD', name: 'Sudan'},
  { code: 'sr', ioc: 'SUR', name: 'Suriname'},
  { code: 'se', ioc: 'SWE', name: 'Sweden'},
  { code: 'ch', ioc: 'SUI', name: 'Switzerland'},
  { code: 'sy', ioc: 'SYR', name: 'Syria'},
  { code: 'tw', ioc: 'TW', name: 'Chinese Taipei'}, // IOC actually TPE, our DB records are incorrect
  { code: 'tj', ioc: 'TJK', name: 'Tajikistan'},
  { code: 'tz', ioc: 'TAN', name: 'Tanzania'},
  { code: 'th', ioc: 'THA', name: 'Thailand'},
  { code: 'tl', ioc: 'TLS', name: 'Timor-Leste'},
  { code: 'tg', ioc: 'TOG', name: 'Togo'},
  { code: 'to', ioc: 'TGA', name: 'Tonga'},
  { code: 'tt', ioc: 'TRI', name: 'Trinidad and Tobago'},
  { code: 'tn', ioc: 'TUN', name: 'Tunisia'},
  { code: 'tr', ioc: 'TUR', name: 'Turkey'},
  { code: 'tm', ioc: 'TKM', name: 'Turkmenistan'},
  { code: 'tv', ioc: 'TUV', name: 'Tuvalu'},
  { code: 'ug', ioc: 'UGA', name: 'Uganda'},
  { code: 'ua', ioc: 'UKR', name: 'Ukraine'},
  { code: 'ae', ioc: 'UAE', name: 'United Arab Emirates'},
  { code: 'gb', ioc: 'GBR', name: 'United Kingdom'},
  { code: 'us', ioc: 'USA', name: 'United States'},
  { code: 'uy', ioc: 'URU', name: 'Uruguay'},
  { code: 'uz', ioc: 'UZB', name: 'Uzbekistan'},
  { code: 'vu', ioc: 'VAN', name: 'Vanuatu'},
  { code: 'va', ioc: 'VAT', name: 'Vatican City'},
  { code: 've', ioc: 'VEN', name: 'Venezuela'},
  { code: 'vn', ioc: 'VIE', name: 'Vietnam'},
  { code: 'ye', ioc: 'YEM', name: 'Yemen'},
  { code: 'zm', ioc: 'ZAM', name: 'Zambia'},
  { code: 'zw', ioc: 'ZIM', name: 'Zimbabwe'},
];

/**
 * Get country by code
 */
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code.toLowerCase() === code.toLowerCase());
}

/**
 * Get country by name
 */
export function getCountryByName(name: string): Country | undefined {
  return COUNTRIES.find(c => c.name.toLowerCase() === name.toLowerCase());
}

/**
 * ISO 3166-1 alpha-2 (lowercase) → IOC 3-letter code mapping.
 * IOC codes differ from ISO-3 for some countries (e.g. de→GER, ch→SUI).
 */
export const ISO2_TO_IOC: Record<string, string> = {
  af: 'AFG', al: 'ALB', dz: 'ALG', ad: 'AND', ao: 'ANG',
  ar: 'ARG', am: 'ARM', au: 'AUS', at: 'AUT', az: 'AZE',
  bs: 'BAH', bh: 'BRN', bd: 'BAN', bb: 'BAR', by: 'BLR',
  be: 'BEL', bz: 'BIZ', bj: 'BEN', bt: 'BHU', bo: 'BOL',
  ba: 'BIH', bw: 'BOT', br: 'BRA', bn: 'BRU', bg: 'BUL',
  bf: 'BUR', bi: 'BDI', cv: 'CPV', kh: 'CAM', cm: 'CMR',
  ca: 'CAN', cf: 'CAF', td: 'CHA', cl: 'CHI', cn: 'CHN',
  co: 'COL', km: 'COM', cg: 'CGO', cr: 'CRC', hr: 'CRO',
  cu: 'CUB', cy: 'CYP', cz: 'CZE', cd: 'COD', dk: 'DEN',
  dj: 'DJI', dm: 'DMA', do: 'DOM', ec: 'ECU', eg: 'EGY',
  sv: 'ESA', gq: 'GEQ', er: 'ERI', ee: 'EST', sz: 'SWZ',
  et: 'ETH', fj: 'FIJ', fi: 'FIN', fr: 'FRA', ga: 'GAB',
  gm: 'GAM', ge: 'GEO', de: 'GER', gh: 'GHA', gr: 'GRE',
  gd: 'GRN', gt: 'GUA', gn: 'GUI', gw: 'GBS', gy: 'GUY',
  ht: 'HAI', hn: 'HON', hu: 'HUN', is: 'ISL', in: 'IND',
  id: 'INA', ir: 'IRI', iq: 'IRQ', ie: 'IRL', il: 'ISR',
  it: 'ITA', jm: 'JAM', jp: 'JPN', jo: 'JOR', kz: 'KAZ',
  ke: 'KEN', ki: 'KIR', kw: 'KUW', kg: 'KGZ', la: 'LAO',
  lv: 'LAT', lb: 'LIB', ls: 'LES', lr: 'LBR', ly: 'LBA',
  li: 'LIE', lt: 'LTU', lu: 'LUX', mg: 'MAD', mw: 'MAW',
  my: 'MAS', mv: 'MDV', ml: 'MLI', mt: 'MLT', mh: 'MHL',
  mr: 'MTN', mu: 'MRI', mx: 'MEX', fm: 'FSM', md: 'MDA',
  mc: 'MON', mn: 'MGL', me: 'MNE', ma: 'MAR', mz: 'MOZ',
  mm: 'MYA', na: 'NAM', nr: 'NRU', np: 'NEP', nl: 'NED',
  nz: 'NZL', ni: 'NCA', ne: 'NIG', ng: 'NGR', kp: 'PRK',
  mk: 'MKD', no: 'NOR', om: 'OMA', pk: 'PAK', pw: 'PLW',
  ps: 'PLE', pa: 'PAN', pg: 'PNG', py: 'PAR', pe: 'PER',
  ph: 'PHI', pl: 'POL', pt: 'POR', qa: 'QAT', ro: 'ROU',
  ru: 'RUS', rw: 'RWA', kn: 'SKN', lc: 'LCA', vc: 'VIN',
  ws: 'SAM', sm: 'SMR', st: 'STP', sa: 'KSA', sn: 'SEN',
  rs: 'SRB', sc: 'SEY', sl: 'SLE', sg: 'SGP', sk: 'SVK',
  si: 'SLO', sb: 'SOL', so: 'SOM', za: 'RSA', kr: 'KOR',
  ss: 'SSD', es: 'ESP', lk: 'SRI', sd: 'SUD', sr: 'SUR',
  se: 'SWE', ch: 'SUI', sy: 'SYR', tj: 'TJK', tz: 'TAN',
  th: 'THA', tl: 'TLS', tg: 'TOG', to: 'TGA', tt: 'TTO',
  tn: 'TUN', tr: 'TUR', tm: 'TKM', tv: 'TUV', ug: 'UGA',
  ua: 'UKR', ae: 'UAE', gb: 'GBR', us: 'USA', uy: 'URU',
  uz: 'UZB', vu: 'VAN', va: 'VAT', ve: 'VEN', vn: 'VIE',
  ye: 'YEM', zm: 'ZAM', zw: 'ZIM',
};

/** Reverse mapping: IOC 3-letter → ISO-2 lowercase */
export const IOC_TO_ISO2: Record<string, string> = Object.fromEntries(
  Object.entries(ISO2_TO_IOC).map(([iso2, ioc]) => [ioc, iso2])
);

/** Convert ISO-2 code (any case) to IOC 3-letter code */
export function getIocCode(iso2: string): string {
  return ISO2_TO_IOC[iso2.toLowerCase()] ?? iso2.toUpperCase();
}

/** Convert IOC 3-letter code to ISO-2 lowercase (for flag libraries) */
export function getIso2FromIoc(ioc: string): string {
  return IOC_TO_ISO2[ioc.toUpperCase()] ?? ioc.toLowerCase();
}
