/**
 * List of countries with their ISO 3166-1 alpha-2 codes
 * Used for country selection and flag display
 */
export interface Country {
  code: string;  // ISO 3166-1 alpha-2 code (lowercase for react-circle-flags)
  name: string;
}

export const COUNTRIES: Country[] = [
  { code: 'af', name: 'Afghanistan' },
  { code: 'al', name: 'Albania' },
  { code: 'dz', name: 'Algeria' },
  { code: 'ad', name: 'Andorra' },
  { code: 'ao', name: 'Angola' },
  { code: 'ar', name: 'Argentina' },
  { code: 'am', name: 'Armenia' },
  { code: 'au', name: 'Australia' },
  { code: 'at', name: 'Austria' },
  { code: 'az', name: 'Azerbaijan' },
  { code: 'bs', name: 'Bahamas' },
  { code: 'bh', name: 'Bahrain' },
  { code: 'bd', name: 'Bangladesh' },
  { code: 'bb', name: 'Barbados' },
  { code: 'by', name: 'Belarus' },
  { code: 'be', name: 'Belgium' },
  { code: 'bz', name: 'Belize' },
  { code: 'bj', name: 'Benin' },
  { code: 'bt', name: 'Bhutan' },
  { code: 'bo', name: 'Bolivia' },
  { code: 'ba', name: 'Bosnia and Herzegovina' },
  { code: 'bw', name: 'Botswana' },
  { code: 'br', name: 'Brazil' },
  { code: 'bn', name: 'Brunei' },
  { code: 'bg', name: 'Bulgaria' },
  { code: 'bf', name: 'Burkina Faso' },
  { code: 'bi', name: 'Burundi' },
  { code: 'cv', name: 'Cabo Verde' },
  { code: 'kh', name: 'Cambodia' },
  { code: 'cm', name: 'Cameroon' },
  { code: 'ca', name: 'Canada' },
  { code: 'cf', name: 'Central African Republic' },
  { code: 'td', name: 'Chad' },
  { code: 'cl', name: 'Chile' },
  { code: 'cn', name: 'China' },
  { code: 'co', name: 'Colombia' },
  { code: 'km', name: 'Comoros' },
  { code: 'cg', name: 'Congo' },
  { code: 'cr', name: 'Costa Rica' },
  { code: 'hr', name: 'Croatia' },
  { code: 'cu', name: 'Cuba' },
  { code: 'cy', name: 'Cyprus' },
  { code: 'cz', name: 'Czech Republic' },
  { code: 'cd', name: 'Democratic Republic of the Congo' },
  { code: 'dk', name: 'Denmark' },
  { code: 'dj', name: 'Djibouti' },
  { code: 'dm', name: 'Dominica' },
  { code: 'do', name: 'Dominican Republic' },
  { code: 'ec', name: 'Ecuador' },
  { code: 'eg', name: 'Egypt' },
  { code: 'sv', name: 'El Salvador' },
  { code: 'gq', name: 'Equatorial Guinea' },
  { code: 'er', name: 'Eritrea' },
  { code: 'ee', name: 'Estonia' },
  { code: 'sz', name: 'Eswatini' },
  { code: 'et', name: 'Ethiopia' },
  { code: 'fj', name: 'Fiji' },
  { code: 'fi', name: 'Finland' },
  { code: 'fr', name: 'France' },
  { code: 'ga', name: 'Gabon' },
  { code: 'gm', name: 'Gambia' },
  { code: 'ge', name: 'Georgia' },
  { code: 'de', name: 'Germany' },
  { code: 'gh', name: 'Ghana' },
  { code: 'gr', name: 'Greece' },
  { code: 'gd', name: 'Grenada' },
  { code: 'gt', name: 'Guatemala' },
  { code: 'gn', name: 'Guinea' },
  { code: 'gw', name: 'Guinea-Bissau' },
  { code: 'gy', name: 'Guyana' },
  { code: 'ht', name: 'Haiti' },
  { code: 'hn', name: 'Honduras' },
  { code: 'hu', name: 'Hungary' },
  { code: 'is', name: 'Iceland' },
  { code: 'in', name: 'India' },
  { code: 'id', name: 'Indonesia' },
  { code: 'ir', name: 'Iran' },
  { code: 'iq', name: 'Iraq' },
  { code: 'ie', name: 'Ireland' },
  { code: 'il', name: 'Israel' },
  { code: 'it', name: 'Italy' },
  { code: 'jm', name: 'Jamaica' },
  { code: 'jp', name: 'Japan' },
  { code: 'jo', name: 'Jordan' },
  { code: 'kz', name: 'Kazakhstan' },
  { code: 'ke', name: 'Kenya' },
  { code: 'ki', name: 'Kiribati' },
  { code: 'kw', name: 'Kuwait' },
  { code: 'kg', name: 'Kyrgyzstan' },
  { code: 'la', name: 'Laos' },
  { code: 'lv', name: 'Latvia' },
  { code: 'lb', name: 'Lebanon' },
  { code: 'ls', name: 'Lesotho' },
  { code: 'lr', name: 'Liberia' },
  { code: 'ly', name: 'Libya' },
  { code: 'li', name: 'Liechtenstein' },
  { code: 'lt', name: 'Lithuania' },
  { code: 'lu', name: 'Luxembourg' },
  { code: 'mg', name: 'Madagascar' },
  { code: 'mw', name: 'Malawi' },
  { code: 'my', name: 'Malaysia' },
  { code: 'mv', name: 'Maldives' },
  { code: 'ml', name: 'Mali' },
  { code: 'mt', name: 'Malta' },
  { code: 'mh', name: 'Marshall Islands' },
  { code: 'mr', name: 'Mauritania' },
  { code: 'mu', name: 'Mauritius' },
  { code: 'mx', name: 'Mexico' },
  { code: 'fm', name: 'Micronesia' },
  { code: 'md', name: 'Moldova' },
  { code: 'mc', name: 'Monaco' },
  { code: 'mn', name: 'Mongolia' },
  { code: 'me', name: 'Montenegro' },
  { code: 'ma', name: 'Morocco' },
  { code: 'mz', name: 'Mozambique' },
  { code: 'mm', name: 'Myanmar' },
  { code: 'na', name: 'Namibia' },
  { code: 'nr', name: 'Nauru' },
  { code: 'np', name: 'Nepal' },
  { code: 'nl', name: 'Netherlands' },
  { code: 'nz', name: 'New Zealand' },
  { code: 'ni', name: 'Nicaragua' },
  { code: 'ne', name: 'Niger' },
  { code: 'ng', name: 'Nigeria' },
  { code: 'kp', name: 'North Korea' },
  { code: 'mk', name: 'North Macedonia' },
  { code: 'no', name: 'Norway' },
  { code: 'om', name: 'Oman' },
  { code: 'pk', name: 'Pakistan' },
  { code: 'pw', name: 'Palau' },
  { code: 'ps', name: 'Palestine' },
  { code: 'pa', name: 'Panama' },
  { code: 'pg', name: 'Papua New Guinea' },
  { code: 'py', name: 'Paraguay' },
  { code: 'pe', name: 'Peru' },
  { code: 'ph', name: 'Philippines' },
  { code: 'pl', name: 'Poland' },
  { code: 'pt', name: 'Portugal' },
  { code: 'qa', name: 'Qatar' },
  { code: 'ro', name: 'Romania' },
  { code: 'ru', name: 'Russia' },
  { code: 'rw', name: 'Rwanda' },
  { code: 'kn', name: 'Saint Kitts and Nevis' },
  { code: 'lc', name: 'Saint Lucia' },
  { code: 'vc', name: 'Saint Vincent and the Grenadines' },
  { code: 'ws', name: 'Samoa' },
  { code: 'sm', name: 'San Marino' },
  { code: 'st', name: 'Sao Tome and Principe' },
  { code: 'sa', name: 'Saudi Arabia' },
  { code: 'sn', name: 'Senegal' },
  { code: 'rs', name: 'Serbia' },
  { code: 'sc', name: 'Seychelles' },
  { code: 'sl', name: 'Sierra Leone' },
  { code: 'sg', name: 'Singapore' },
  { code: 'sk', name: 'Slovakia' },
  { code: 'si', name: 'Slovenia' },
  { code: 'sb', name: 'Solomon Islands' },
  { code: 'so', name: 'Somalia' },
  { code: 'za', name: 'South Africa' },
  { code: 'kr', name: 'South Korea' },
  { code: 'ss', name: 'South Sudan' },
  { code: 'es', name: 'Spain' },
  { code: 'lk', name: 'Sri Lanka' },
  { code: 'sd', name: 'Sudan' },
  { code: 'sr', name: 'Suriname' },
  { code: 'se', name: 'Sweden' },
  { code: 'ch', name: 'Switzerland' },
  { code: 'sy', name: 'Syria' },
  { code: 'tj', name: 'Tajikistan' },
  { code: 'tz', name: 'Tanzania' },
  { code: 'th', name: 'Thailand' },
  { code: 'tl', name: 'Timor-Leste' },
  { code: 'tg', name: 'Togo' },
  { code: 'to', name: 'Tonga' },
  { code: 'tt', name: 'Trinidad and Tobago' },
  { code: 'tn', name: 'Tunisia' },
  { code: 'tr', name: 'Turkey' },
  { code: 'tm', name: 'Turkmenistan' },
  { code: 'tv', name: 'Tuvalu' },
  { code: 'ug', name: 'Uganda' },
  { code: 'ua', name: 'Ukraine' },
  { code: 'ae', name: 'United Arab Emirates' },
  { code: 'gb', name: 'United Kingdom' },
  { code: 'us', name: 'United States' },
  { code: 'uy', name: 'Uruguay' },
  { code: 'uz', name: 'Uzbekistan' },
  { code: 'vu', name: 'Vanuatu' },
  { code: 'va', name: 'Vatican City' },
  { code: 've', name: 'Venezuela' },
  { code: 'vn', name: 'Vietnam' },
  { code: 'ye', name: 'Yemen' },
  { code: 'zm', name: 'Zambia' },
  { code: 'zw', name: 'Zimbabwe' },
];

/**
 * Get country by code
 */
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code.toLowerCase() === code.toLowerCase());
}

/**
 * Get country by name
 */
export function getCountryByName(name: string): Country | undefined {
  return COUNTRIES.find(c => c.name.toLowerCase() === name.toLowerCase());
}

/**
 * ISO 3166-1 alpha-2 (lowercase) → IOC 3-letter code mapping.
 * IOC codes differ from ISO-3 for some countries (e.g. de→GER, ch→SUI).
 */
export const ISO2_TO_IOC: Record<string, string> = {
  af: 'AFG', al: 'ALB', dz: 'ALG', ad: 'AND', ao: 'ANG',
  ar: 'ARG', am: 'ARM', au: 'AUS', at: 'AUT', az: 'AZE',
  bs: 'BAH', bh: 'BRN', bd: 'BAN', bb: 'BAR', by: 'BLR',
  be: 'BEL', bz: 'BIZ', bj: 'BEN', bt: 'BHU', bo: 'BOL',
  ba: 'BIH', bw: 'BOT', br: 'BRA', bn: 'BRU', bg: 'BUL',
  bf: 'BUR', bi: 'BDI', cv: 'CPV', kh: 'CAM', cm: 'CMR',
  ca: 'CAN', cf: 'CAF', td: 'CHA', cl: 'CHI', cn: 'CHN',
  co: 'COL', km: 'COM', cg: 'CGO', cr: 'CRC', hr: 'CRO',
  cu: 'CUB', cy: 'CYP', cz: 'CZE', cd: 'COD', dk: 'DEN',
  dj: 'DJI', dm: 'DMA', do: 'DOM', ec: 'ECU', eg: 'EGY',
  sv: 'ESA', gq: 'GEQ', er: 'ERI', ee: 'EST', sz: 'SWZ',
  et: 'ETH', fj: 'FIJ', fi: 'FIN', fr: 'FRA', ga: 'GAB',
  gm: 'GAM', ge: 'GEO', de: 'GER', gh: 'GHA', gr: 'GRE',
  gd: 'GRN', gt: 'GUA', gn: 'GUI', gw: 'GBS', gy: 'GUY',
  ht: 'HAI', hn: 'HON', hu: 'HUN', is: 'ISL', in: 'IND',
  id: 'INA', ir: 'IRI', iq: 'IRQ', ie: 'IRL', il: 'ISR',
  it: 'ITA', jm: 'JAM', jp: 'JPN', jo: 'JOR', kz: 'KAZ',
  ke: 'KEN', ki: 'KIR', kw: 'KUW', kg: 'KGZ', la: 'LAO',
  lv: 'LAT', lb: 'LIB', ls: 'LES', lr: 'LBR', ly: 'LBA',
  li: 'LIE', lt: 'LTU', lu: 'LUX', mg: 'MAD', mw: 'MAW',
  my: 'MAS', mv: 'MDV', ml: 'MLI', mt: 'MLT', mh: 'MHL',
  mr: 'MTN', mu: 'MRI', mx: 'MEX', fm: 'FSM', md: 'MDA',
  mc: 'MON', mn: 'MGL', me: 'MNE', ma: 'MAR', mz: 'MOZ',
  mm: 'MYA', na: 'NAM', nr: 'NRU', np: 'NEP', nl: 'NED',
  nz: 'NZL', ni: 'NCA', ne: 'NIG', ng: 'NGR', kp: 'PRK',
  mk: 'MKD', no: 'NOR', om: 'OMA', pk: 'PAK', pw: 'PLW',
  ps: 'PLE', pa: 'PAN', pg: 'PNG', py: 'PAR', pe: 'PER',
  ph: 'PHI', pl: 'POL', pt: 'POR', qa: 'QAT', ro: 'ROU',
  ru: 'RUS', rw: 'RWA', kn: 'SKN', lc: 'LCA', vc: 'VIN',
  ws: 'SAM', sm: 'SMR', st: 'STP', sa: 'KSA', sn: 'SEN',
  rs: 'SRB', sc: 'SEY', sl: 'SLE', sg: 'SGP', sk: 'SVK',
  si: 'SLO', sb: 'SOL', so: 'SOM', za: 'RSA', kr: 'KOR',
  ss: 'SSD', es: 'ESP', lk: 'SRI', sd: 'SUD', sr: 'SUR',
  se: 'SWE', ch: 'SUI', sy: 'SYR', tj: 'TJK', tz: 'TAN',
  th: 'THA', tl: 'TLS', tg: 'TOG', to: 'TGA', tt: 'TTO',
  tn: 'TUN', tr: 'TUR', tm: 'TKM', tv: 'TUV', ug: 'UGA',
  ua: 'UKR', ae: 'UAE', gb: 'GBR', us: 'USA', uy: 'URU',
  uz: 'UZB', vu: 'VAN', va: 'VAT', ve: 'VEN', vn: 'VIE',
  ye: 'YEM', zm: 'ZAM', zw: 'ZIM',
};

/** Reverse mapping: IOC 3-letter → ISO-2 lowercase */
export const IOC_TO_ISO2: Record<string, string> = Object.fromEntries(
  Object.entries(ISO2_TO_IOC).map(([iso2, ioc]) => [ioc, iso2])
);

/** Convert ISO-2 code (any case) to IOC 3-letter code */
export function getIocCode(iso2: string): string {
  return ISO2_TO_IOC[iso2.toLowerCase()] ?? iso2.toUpperCase();
}

/** Convert IOC 3-letter code to ISO-2 lowercase (for flag libraries) */
export function getIso2FromIoc(ioc: string): string {
  return IOC_TO_ISO2[ioc.toUpperCase()] ?? ioc.toLowerCase();
}
